### ISSUE TITLE
It's still making requests to the thumbnail sites

### ISSUE THREAD

**Issue by kiproping** [FunToUse/Hide-Most-Visited-Pages-Reloaded#3]
I know the purpose is to hide the list but it's still loading the thumbnails behind the scenes. 

I am seeing such requests in the console 

`chrome-search://thumb2/https://www.reddit.com/r/the_donald`

`https://s2.googleusercontent.com/s2/favicons?domain_url=https%3A%2F%2Fnews.ycombinator.com%2F&alt=s&sz=32&src=chrome_newtab`

Do you plan to remove those?

Also I hate these google messages.

> It's spring cleaning time. Check out our 10 online safety tips.

**Comment by kiproping** [comment]
I fixed the google messages thing. https://github.com/kiproping/Hide-Most-Visited-Pages-Reloaded/commit/f477cd5137c555b6c7be1763f281130ef2b45480. Should it be like an option thing or what?

**Comment by mkx64** [comment]
Yes, it should be optional, please.

**Comment by BabbaFresh** [comment]
Closing this as this merge request isn't valid anymore. It can't be merged due to major changes. But you made a valid point though! I'm going to push a version to the store where it won't load the thumbnails and you can hide those google messages, soon :) :+1: Thanks!
